### ISSUE TITLE
Firefox port

### ISSUE THREAD

**Issue by rugk** [Tshetrim/Image-To-Text-OCR-extension-for-ChatGPT#1]
It would be great if you could port your browser extension from Chrome/ium also to other browsers like Firefox, i.e. making it a cross-compatible browser extension (“WebExtension”).

See https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/ for more information on how to do that.

The reason why I am asking is that the previously linked Firefox extension is apparently unmaintained(?), see https://github.com/gnonio/korporize/issues/14 (ref https://github.com/naptha/tesseract.js/issues/807) and also like in general maintaining one codebase should be easier than maintaining it twice.

**Comment by Tshetrim** [comment]
Hi, I just submitted it and am waiting for it to be approved for Firefox!

**Comment by rugk** [comment]
Awesome! So if it is, could you also link it from the Readme, so people can find it? You can also use these download badges here: https://extensionworkshop.com/documentation/publish/promoting-your-extension/

**Comment by Tshetrim** [comment]
It got approval and I updated the Readme with a download badge to the Firefox addon. Thank you for the suggestions and help! 

https://addons.mozilla.org/en-US/firefox/addon/image-to-text-chatgpt/
