### ISSUE TITLE
How to add another language?

### ISSUE THREAD

**Issue by sornay** [Tshetrim/Image-To-Text-OCR-extension-for-ChatGPT#2]
Hi,
I wanted to add another language.
I edited the content.js and added the language name and language code there.
Also added traineddata into the languages folder.
Nothing happened.

**Comment by Tshetrim** [comment]
Hi, 

Can you confirm if the new language is showing up as an option in the language options after you made the changes? If you're on Chrome, you do have to reload the unpacked extension itself and reload the page for the changes to take effect. 

If you can see the new language in the language options, then there's probably a different issue, including 

- making sure trained data is in .gz format 
- you got it from this link: https://tesseract-ocr.github.io/tessdoc/Data-Files#data-files-for-version-400-november-29-2016 
- and making sure they're the 4.0 trained data version

I have a feeling its the former of the changes not having been loaded but let me know if it helps.

**Comment by sornay** [comment]
I wasn't sure how to reload the extension at first, so I reinstall it.
After that, I replaced the trained data with the version 4 trained data from the link you provided and
reload the unpacked extension, it seems that it works perfectly fine now.
Thanks for the help

**Comment by Tshetrim** [comment]
Great to hear, glad it worked out!
