### ISSUE TITLE
Japanese Supported

### ISSUE THREAD

**Issue by Naikkusu** [Tshetrim/Image-To-Text-OCR-extension-for-ChatGPT#4]
Hi, can you add in the OCR, Japanese (Vertical)

**Comment by Tshetrim** [comment]
Hi apologies for the late response but I don't believe vertical is available with the OCR version I'm using. 

https://tesseract-ocr.github.io/tessdoc/Data-Files#data-files-for-version-400-november-29-2016

I did see that vert is available here:
https://github.com/tesseract-ocr/tessdata/blob/main/jpn_vert.traineddata

You can try to download the .gz version, then drop it into the languages folder:
https://github.com/Tshetrim/Image-To-Text-OCR-extension-for-ChatGPT/tree/main/scripts/languages

And then load the extension locally on your own. 

On Chrome: 
1. Download the extension zip file of this code base (or clone it and skip step 2)
2. Extract the files into a folder 
3. Go to chrome://extensions/ in Chrome 
4. Turn on Developer mode in the top right corner 
5. Click Load unpacked 
6. Select the extension folder
